name: Test and Build Packages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build Packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

#    - name: Run linting
#      run: npm run lint

    - name: Run type checking
      run: npm run typecheck

    - name: Build packages
      run: npm run build

    - name: Run tests
      run: npm run test

  build-and-test-cli:
    name: Build and Test CLI
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build CLI package
      run: npm run build:cli

    - name: Test CLI functionality
      run: |
        cd packages/cli
        node dist/index.js extract "examples/**/*.tsx" --output test-output.json
        cat test-output.json
